language: go
install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libglu1-mesa-dev libgles2-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev
go:
  - "1.x"
script:
  - GO111MODULE=on go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
